export {Jumbotron} from './jumbotron';
export {Loading} from './loading';
export {Profiles} from './profiles';
export {Form} from './form';
export {Feature} from './feature';
export {Header} from '../header';
export {OptForm} from './opt-form';
export {Accordion} from './acordion';
export {Footer} from '../footer';
